---
title: "EGI Simulations"
author: "A.Nuur"
date: "2/16/2022"
output: html_document
---
packages
```{r}
library(ggplot2); library(tidyverse); library(readxl)
```
Parameters
```{r}
#Parameter
s<- 0.25
n <- 0.03
alpha <- 0.33
dep_rate <- 0.04
g <- 0.02

```
Initial values
```{r}
#Initial values
L0 <- 45.00
K0 <- 1075795.25
k0 <- K0/L0
A0 <- 10862.74
Y0 <- K0^(alpha) * (A0*L0)^(1-alpha)
year <- seq(2020, 2100, 1)
period <- 1:81 
```
Step1 calculate population and technology level
```{r}
#Population, L
L <- rep(NA, 81)
A <- rep(NA, 81)
L[1]<- L0
A[1]<- A0
for(i in 2:81){
  L[i]<- L[i-1]*exp(n)
  A[i]<- A[i-1]*exp(g)
}

A
```
Step2 calculate physical capital, physical cpaital per worker, then gdpPercap
```{r}
K <- rep(NA, 81)
k <- rep(NA, 81)
Y <- rep(NA, 81)
y<- rep(NA, 81)
y_growth <- rep(NA, 81)
K[1]<- K0
k[1]<- k0
Y[1]<- Y0
y[1]<- (Y0/L0)
y_growth[1 ]<- (y[2]- y[1]) / y[1]

for(i in 2:81){
  K[i]<- (1-dep_rate)*K[i-1] + s*Y[i-1]
  Y[i] <- K[i]^(alpha) * (A[i]*L[i])^(1-alpha)
  k[i] <- (K[i]/L[i])
  y[i] <- (Y[i])/ L[i]
  y_growth[i] <- (y[i] -y[i-1]) / y[i-1] 
}
plot.ts(y_growth)
#Period is fishy


```
dataframe 
```{r}
sim_1 <- data.frame(year, period, A, L,K, Y, y_growth)
```

