---
title: 'Economic Growth and Institutions: Assignment 1'
author: "Mathieu Van der Vel, Abdirahman Nuur and Maximilian Grotz"
date: "14 2 2022"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Introduction

```{r}
library(tidyverse)
```

# Introduction

```{r}
# Parameters
s = .25
delta = .04
alpha = .33
n = .03
g = .02

# y_sim1 in 2017 USD (PPP), K_sim1 in mill 2017 USD (PPP), A_sim1 in index
L_0 = 45.0
K_0 = 1075795.25
A_0 = 10862.74
```

# Simulation 1
Abdo Checked
```{r}
sim1 <- data.frame(year = 2020:2100,
                   L = L_0,
                   K_sim1 = K_0,
                   A_sim1 = A_0,
                   yhat_sim1 = NA,
                   Y_sim1 = K_0^alpha*(A_0*L_0)^(1-alpha),
                   y_sim1 = K_0^alpha*(A_0*L_0)^(1-alpha)/L_0)

# Start calculating values
sim1 <- sim1 %>%
  mutate(L = L_0*exp(n*(year-2020)))

for (i in 2:nrow(sim1)) {
  sim1$A_sim1[i] <- sim1$A_sim1[i-1]*exp(g)
  sim1$K_sim1[i] <- (1-delta)*sim1$K_sim1[i-1] + s*sim1$Y_sim1[i-1]
  sim1$Y_sim1[i] <- sim1$K_sim1[i]^alpha*(sim1$L[i]*sim1$A_sim1[i])^(1-alpha)
  sim1$y_sim1[i] <- sim1$Y_sim1[i]/sim1$L[i]
  sim1$yhat_sim1[i] <- (sim1$y_sim1[i]-sim1$y_sim1[i-1])/sim1$y_sim1[i-1]
}
sim1 <- sim1%>%
  mutate_if(is.numeric, round, digits= 3)

ggplot(data = sim1, aes(x = year, y = yhat_sim1)) +
  geom_line()
```

# Simulation 2

```{r}
set.seed(420)
pi <- 0.05
theta <- 0.05
year <- c(2020:2100)
#Why not rbinom()??
W_sim2 <- as.integer(lapply(runif(length(year)), function(x) ifelse(x<pi, 1, 0)))


### Expected [E] ###

sim2_E <- data.frame(year = 2020:2100,
                   W = W_sim2,
                   L = L_0,
                   K_sim2 = K_0,
                   A_sim2 = A_0,
                   yhat_sim2 = NA, 
                   pi = pi)

sim2_E <- sim2_E %>%
  mutate(L = L_0*exp(n*(year-2020)))

sim2_E <- sim2_E %>%
  mutate(Y_sim2 = K_0^alpha*(A_sim2*L_0)^(1-alpha),
                   y_sim2 = K_0^alpha*(A_sim2*L_0)^(1-alpha)/L_0)

for (i in 2:nrow(sim2_E)) {
  sim2_E$A_sim2[i] <- sim2_E$A_sim2[i-1]*exp(g)*(1-sim2_E$pi[i]*theta)
  sim2_E$K_sim2[i] <- (1-delta)*sim2_E$K_sim2[i-1] + s*sim2_E$Y_sim2[i-1]
  sim2_E$Y_sim2[i] <- sim2_E$K_sim2[i]^alpha*(sim2_E$L[i]*sim2_E$A_sim2[i])^(1-alpha)
  sim2_E$y_sim2[i] <- sim2_E$Y_sim2[i]/sim2_E$L[i]
  sim2_E$yhat_sim2[i] <- (sim2_E$y_sim2[i]-sim2_E$y_sim2[i-1])/sim2_E$y_sim2[i-1]
}
sim2_E <- sim2_E%>%
  mutate_if(is.numeric, round, digits= 3)

### Random realisation [RR] ###

sim2_RR <- data.frame(year = 2020:2100,
                   W = W_sim2,
                   L = L_0,
                   K_sim2 = K_0,
                   A_sim2 = A_0,
                   yhat_sim2 = NA)

sim2_RR <- sim2_RR %>%
  mutate(L = L_0*exp(n*(year-2020)))

sim2_RR <- sim2_RR %>%
  mutate( Y_sim2 = K_0^alpha*(A_sim2*L_0)^(1-alpha),
                   y_sim2 = K_0^alpha*(A_sim2*L_0)^(1-alpha)/L_0)

for (i in 2:nrow(sim2_RR)) {
  sim2_RR$A_sim2[i] <- sim2_RR$A_sim2[i-1]*exp(g)*(1-(sim2_RR$W[i]*theta))
  sim2_RR$K_sim2[i] <- (1-delta)*sim2_RR$K_sim2[i-1] + s*sim2_RR$Y_sim2[i-1]
  sim2_RR$Y_sim2[i] <- sim2_RR$K_sim2[i]^alpha*(sim2_RR$L[i]*sim2_RR$A_sim2[i])^(1-alpha)
  sim2_RR$y_sim2[i] <- sim2_RR$Y_sim2[i]/sim2_RR$L[i]
  sim2_RR$yhat_sim2[i] <- (sim2_RR$y_sim2[i]-sim2_RR$y_sim2[i-1])/sim2_RR$y_sim2[i-1]
}
sim2_RR <- sim2_RR%>%
  mutate_if(is.numeric, round, digits= 3)
```

# Simulation 3

```{r}
### Expected [E] ###
pi_sim3 <- rep(NA, 81)
pi_sim3[1:31] <- seq( 0.050,0.20, by=0.005)
pi_sim3[32:81] <- 0.20

sim3_E <- data.frame(year = 2020:2100,
                   L = L_0,
                   K = K_0,
                   A = A_0,
                   yhat = NA, 
                   pi = pi_sim3)

sim3_E <- sim3_E %>%
  mutate(L = L_0*exp(n*(year-2020)))

sim3_E <- sim3_E %>%
  mutate(Y_sim2 = K_0^alpha*(A*L_0)^(1-alpha),
                   y = K_0^alpha*(A*L_0)^(1-alpha)/L_0)

for (i in 2:nrow(sim3_E)) {
  sim3_E$A[i] <- sim3_E$A[i-1]*exp(g)*(1-sim3_E$pi[i]*theta)
  sim3_E$K[i] <- (1-delta)*sim3_E$K[i-1] + s*sim3_E$Y[i-1]
  sim3_E$Y[i] <- sim3_E$K[i]^alpha*(sim3_E$L[i]*sim3_E$A[i])^(1-alpha)
  sim3_E$y[i] <- sim3_E$Y[i]/sim3_E$L[i]
  sim3_E$yhat[i] <- (sim3_E$y[i]-sim3_E$y[i-1])/sim3_E$y[i-1]
}

sim3_E <- sim3_E%>%
  mutate_if(is.numeric, round, digits= 3)
### Random realisation [RR] ###

W_sim3 <- as.integer(runif(length(2020:2100)) < pi_sim3)

sim3_RR <- data.frame(year = 2020:2100,
                   W = W_sim3,
                   L = L_0,
                   K = K_0,
                   A = A_0,
                   yhat = NA)

sim3_RR <- sim3_RR %>%
  mutate(L = L_0*exp(n*(year-2020)))

sim3_RR <- sim3_RR %>%
  mutate( Y_sim2 = K_0^alpha*(A*L_0)^(1-alpha),
                   y = K_0^alpha*(A*L_0)^(1-alpha)/L_0)


for (i in 2:nrow(sim3_RR)) {
  sim3_RR$A[i] <- sim3_RR$A[i-1]*exp(g)*(1-sim3_RR$W[i]*theta)
  sim3_RR$K[i] <- (1-delta)*sim3_RR$K[i-1] + s*sim3_RR$Y[i-1]
  sim3_RR$Y[i] <- sim3_RR$K[i]^alpha*(sim3_RR$L[i]*sim3_RR$A[i])^(1-alpha)
  sim3_RR$y[i] <- sim3_RR$Y[i]/sim3_RR$L[i]
  sim3_RR$yhat[i] <- (sim3_RR$y[i]-sim3_RR$y[i-1])/sim3_RR$y[i-1]
}
sim3_RR <- sim3_RR%>%
  mutate_if(is.numeric, round, digits= 3)
```

# Simulation 4

```{r}
s_b <- .02
theta_l <- .01
theta_u <- .05
B_0 <- 0

sim4 <- data.frame(year = 2020:2100,
                   W = W_sim3,
                   L = L_0,
                   K = K_0,
                   A = A_0,
                   yhat = NA, 
                   B = B_0, 
                   Y_sim3 = sim3_RR$Y, 
                   D = NA)

sim4 <- sim4 %>%
  mutate(L = L_0*exp(n*(year-2020)))

sim4 <- sim4 %>%
  mutate( Y = K_0^alpha*(A*L_0)^(1-alpha),
          y =Y/L_0, 
          C = (1-s-s_b)*Y, 
          C_sim3 = (1-s)*Y_sim3, 
          C_over_Csim3 = C/C_sim3)


for (i in 2:nrow(sim4)) {
  sim4$B[i] <- sim4$B[i-1] + s_b*sim4$Y[i] - delta * sim4$B[i-1]
  sim4$D[i] <- theta_l + (theta_u - theta_l)*exp(-.1*sim4$B[i]/sim4$A[i-1])
  sim4$A[i] <- sim4$A[i-1]*exp(g)*(1-sim4$W[i]*sim4$D[i])
  sim4$K[i] <- (1-delta)*sim4$K[i-1] + s*sim4$Y[i-1]
  sim4$Y[i] <- sim4$K[i]^alpha*(sim4$L[i]*sim4$A[i])^(1-alpha)
  sim4$C[i] <- (1 - s - s_b)*sim4$Y[i]
  sim4$y[i] <- sim4$Y[i]/sim4$L[i]
  sim4$yhat[i] <- (sim4$y[i]-sim4$y[i-1])/sim4$y[i-1]
  sim4$C_over_Csim3[i] <- sim4$C[i]/sim4$C_sim3[i] 
}
sim4 <- sim4%>%
  mutate_if(is.numeric, round, digits= 3)

ggplot(data = sim4) +
  geom_line(aes(x = year, y = C_over_Csim3))
```
## Writing the code into xlsx
```{r}
library(writexl)


write_xlsx(list(Simulation1= sim1, Simulation2E= sim2_E, Simulation2RR= sim2_RR, Simulation3E= sim3_E, Simulation3RR= sim3_RR, simulation4 = sim4), col_names = TRUE, "EGI: Assignment1.xlsx")
```

